version: '3'
services:
  elasticsearch:
    image: elasticsearch:6.4.1
    container_name: elastic
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - $PWD/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - "es-data:/usr/share/elasticsearch/data"
    networks:
      - network1

  logstash:
    image: logstash:5.6.12
    container_name: logstash
    command: logstash -f /config/
    volumes:
      - $PWD/logstash/config:/config
    networks:
      - network1
    depends_on:
      - elasticsearch
      
  kibana:
    image: kibana:5.1.2
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - $PWD/kibana/config/kibana.yml:/etc/kibana/kibana.yml
    networks:
      - network1
    depends_on:
      - elasticsearch

volumes:
   es-data:
    driver: local

networks:
   network1: